version: '3'

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  postgres_db_vol:
  pgadmin-data:

services:

  db_postgres:
    image: postgres:latest
    container_name: postgres_db_container
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_vol:/var/lib/postgresql/data

  gdz_bot:
    restart: unless-stopped
    build: ./
    env_file:
      - .env
    environment:
      - TOKEN
